services:
  - type: web
    name: ecg-api
    env: python
    runtime: python3.10
    buildCommand: |
      pip install "pip<24.1"
      pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    autoDeploy: true
